Feat: Swagger Docs
scooby-doo-cade-voce/backend pull request #18
Opened 2024-05-18 15:36 UTC by andredifs

# PR para o issue https://github.com/scooby-doo-cade-voce/backend/issues/14

Adicionado:
- Configuração básica para o docs da api via Swagger
- Configuração da CLI Plugin do Swagger no Nest

Para testar basta acessar o https://localhost:3000/api

2024-05-19 17:09 UTC, leosimao approved these changes

2024-05-19 17:28 UTC, leosimao reviewed
Opa, tudo beem? Obrigado por sua contribuição!!
Peço apenas que na sua máquina crie uma branch a partir de master e peça a PR a partir dessa sua branch para master, apenas essa alteração.

Obrigado novamente pela contribuição!

2024-05-19 18:10 UTC, leosimao approved these changes

2024-05-19 21:09 UTC, leosimao requested changes
Coloquei como comentário, porém é como Request Changes

2024-05-20 03:24 UTC, vanessasoutoc approved these changes

2024-05-20 03:28 UTC, merged