Feat: Validações dos campos // Swagger
scooby-doo-cade-voce/backend pull request #31
Opened 2024-05-24 00:53 UTC by JoaoVitorJJV

Aberta para a issue: Validar campos ao realizar novo cadastro de animal. #22
Essa PR irá adicionar as validações necessárias, sem utilização de bibliotecas externas. Fiz também algumas correções na documentação do Swagger:

```javascript
@ApiParam({
    name: 'responsible',
    type: ResponsibleDto,
    description: 'Here goes the responsible_id of animal',
    example: {
      name: 'Joãozinho',
      cellhpone: '1234567',
      email: 'teste@gmail.com',
    },
    required: true,
  })

2024-05-24 22:35 UTC, leosimao reviewed
opa tudo certo?
Da uma olhada na documentação do NestJs sobre validação que são a class-validator e class-transform, neles possui umas tags que facilita bastante para a gente realizar a validação 

https://docs.nestjs.com/techniques/validation

2024-05-24 23:06 UTC, JoaoVitorJJV commented
> opa tudo certo? Da uma olhada na documentação do NestJs sobre validação que são a class-validator e class-transform, neles possui umas tags que facilita bastante para a gente realizar a validação
> 
> https://docs.nestjs.com/techniques/validation

Eu havia visto sobre isso. Mas teria que baixar uma biblioteca externa

2024-05-27 15:31 UTC, vanessasoutoc requested changes
@JoaoVitorJJV 
Precisa corrigir os erros de eslint e testes.

2024-05-27 16:30 UTC, JoaoVitorJJV commented
> @JoaoVitorJJV Precisa corrigir os erros de eslint e testes.

Prontinho 😀

2024-05-27 19:04 UTC, vanessasoutoc approved these changes

2024-05-27 19:04 UTC, merged